### ISSUE TITLE
how to define a rule dag

### ISSUE THREAD

**Issue by guanguoyintao** [bytedance/arishem#11]
my scenario is to have a rule set where each rule can be considered as an operator, and to combine these rules with a DAG.
each rule has inputs and outputs, and DAG associates the inputs and outputs of these rules to obtain the final calculation result.
![image](https://github.com/bytedance/arishem/assets/59548482/3eeb5ba8-4172-4af1-8e67-d383fef3988d)
![image](https://github.com/bytedance/arishem/assets/59548482/42964770-3df2-4109-982f-8551d87b5eb6)
![image](https://github.com/bytedance/arishem/assets/59548482/4781d777-8eb1-45b0-bc35-11db28d40913)

**Comment by guanguoyintao** [comment]
please give me any DAG rule demo for golang.

**Comment by AoranAllen** [comment]
> my scenario is to have a rule set where each rule can be considered as an operator, and to combine these rules with a DAG. each rule has inputs and outputs, and DAG associates the inputs and outputs of these rules to obtain the final calculation result. ![image](https://user-images.githubusercontent.com/59548482/257502869-3eeb5ba8-4172-4af1-8e67-d383fef3988d.png) ![image](https://user-images.githubusercontent.com/59548482/257502897-42964770-3df2-4109-982f-8551d87b5eb6.png) ![image](https://user-images.githubusercontent.com/59548482/257502907-4781d777-8eb1-45b0-bc35-11db28d40913.png)

你的意思是想要自定义每条规则的优先级然后组合运算他们吗？

**Comment by yanwii** [comment]
确实需要编排规则，目前好像没有看到代码中有类似的接口

**Comment by AoranAllen** [comment]
> 确实需要编排规则，目前好像没有看到代码中有类似的接口

目前arishem不支持DAG模式，但是支持自定义规则的优先级，可以自己实现RuleTarget接口看看能不能满足目前的业务场景呢，参考自定义规则优先级部分：https://github.com/bytedance/arishem/blob/main/doc/zh/RULE_zh.md

**Comment by AoranAllen** [comment]
cause there's no latest reply, i'll close this issue.
