### ISSUE TITLE
是否有根据JSON转为SQL查询语句的计划

### ISSUE THREAD

**Issue by iiiusky** [bytedance/arishem#14]
是否有根据JSON转为SQL查询语句的计划？
可以输出原始SQL语句或者gorm的查询条件对象

**Comment by AoranAllen** [comment]
这并不是一个规则引擎核心判断能力的一部分，并且考虑到生成SQL语句在不同平台的兼容性以及arishem支持的下游参数和自定义Func能力，实现起来的复杂度较高，所以arishem团队在短期内没有支持的计划
