### ISSUE TITLE
能否提供foreach的能力，支持对List中每个元素按照配置指定的condition进行规则判断

### ISSUE THREAD

**Issue by bailp** [bytedance/arishem#16]
背景如下： 有类似如下的一个业务数据，
`
{
    "Products": [
        {
            "ProductCode": "P1",
            "Config": "C1",
            "Region": "beijing",
            "Quantity": 5,
            "IsAccountNew": 1
        },
        {
            "ProductCode": "P2",
            "Config": "C2",
            "Region": "shanghai",
            "Quantity": 2,
            "IsAccountNew": 1
        },
        {
            "ProductCode": "P3",
            "Config": "C3",
            "Region": "guanzhou",
            "Quantity": 2,
            "IsAccountNew": 1
        }
    ],
    "Order": {
        "Type": 1
    }
}
`

期望能实现一种类似foreach的Expr：对Products这样子一个list中的每个元素都进行一个指定规则组的检查，比对如上的数据，能表达这样的规则

`foreach Products as P:
(P.ProductCode==P1 && P.Quantity>=1 && P.Region="beijing") || (P.ProductCode==P2 && P.Quantity >= 2) || (P.ProductCode==P3 && P.Quantity>=1)`

**Comment by AoranAllen** [comment]
我们预计提供这样一种foreach的条件组合操作符：foreach + (${任意操作符} 或 SubRule) + (逻辑与或)，其中：
1. 任意操作符是arishem已定义的：比如 >=、!=、LIST_IN
2. SubRule指针对每个foreach入参，执行一次子规则的判断，如下形式
```json
{
    "Operator": "foreach sub_rules and",
    "Lhs": {
        "VarExpr": "$products"
    },
    "Rhs": {
        "SubRules": "my_sub_rule"
    }
}
```
上述的详细方案团队还在讨论中，但预计很快将会实行
